### ISSUE TITLE
nil

### ISSUE THREAD

**Issue by Nasfame** [bacalhau-project/lilypad#20]
```shell
lilypad_run_decenter_module run github.com/DeCenter-AI/compute.decenter-ai:v1.7.1-alpha -i trainScript=headbrain.ipynb -i inputCid=Qme1HnwLHVzRxra7mT5gRkG7WbyE4FhnGFn9inETSj33Hw
```
```

⠀⠀⠀⠀⠀⠀⣀⣤⣤⢠⣤⣀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢴⣿⣿⣿⣿⢸⣿⡟⠀⠀⠀⠀⠀    ██╗     ██╗██╗  ██╗   ██╗██████╗  █████╗ ██████╗ 
⠀⠀⣰⣿⣦⡙⢿⣿⣿⢸⡿⠀⠀⠀⠀⢀⠀    ██║     ██║██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
⠀⢰⣿⣿⣿⣿⣦⡙⣿⢸⠁⢀⣠⣴⣾⣿⡆    ██║     ██║██║   ╚████╔╝ ██████╔╝███████║██║  ██║
⠀⣛⣛⣛⣛⣛⣛⣛⠈⠀⣚⣛⣛⣛⣛⣛⣛    ██║     ██║██║    ╚██╔╝  ██╔═══╝ ██╔══██║██║  ██║
⠀⢹⣿⣿⣿⣿⠟⣡⣿⢸⣮⡻⣿⣿⣿⣿⡏    ███████╗██║███████╗██║   ██║     ██║  ██║██████╔╝
⠀⠀⢻⣿⡟⣩⣾⣿⣿⢸⣿⣿⣌⠻⣿⡟⠀    ╚══════╝╚═╝╚══════╝╚═╝   ╚═╝     ╚═╝  ╚═╝╚═════╝ v2
⠀⠀⠀⠉⢾⣿⣿⣿⣿⢸⣿⣿⣿⡷⠈⠀⠀                                                  
⠀⠀⠀⠀⠀⠈⠙⠛⠛⠘⠛⠋⠁⠀ ⠀⠀⠀   Decentralized Compute Network  https://lilypad.tech

🌟  Lilypad submitting job
2023-10-23T23:11:04+05:30 INF pkg/module/utils.go:149 > updating cached git repo=data/repos/DeCenter-AI/compute.decenter-ai
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1013ad6f4]

goroutine 1 [running]:
text/template.(*Template).init(...)
        /usr/local/go/src/text/template/template.go:71
text/template.(*Template).Funcs(0x0, 0x1400062e6f8?)
        /usr/local/go/src/text/template/template.go:178 +0x34
github.com/bacalhau-project/lilypad/pkg/module.LoadModule({{0x0, 0x0}, {0x140001afdc0, 0x32}, {0x16ee23384, 0xc}, {0x1017059e9, 0x19}}, 0x1400043c030?)
        /Users/hiro/Decenter/lilypad/pkg/module/utils.go:222 +0x290
github.com/bacalhau-project/lilypad/pkg/jobcreator.(*JobCreator).GetJobOfferFromOptions(_, {{{0x0, 0x0}, {0x140001afdc0, 0x32}, {0x16ee23384, 0xc}, {0x1017059e9, 0x19}}, {0x0, ...}, ...})
        /Users/hiro/Decenter/lilypad/pkg/jobcreator/jobcreator.go:76 +0x64
github.com/bacalhau-project/lilypad/pkg/jobcreator.RunJob(_, {{0x0}, {{{0x0, 0x0}, {0x140001afdc0, 0x32}, {0x16ee23384, 0xc}, {0x1017059e9, 0x19}}, ...}, ...}, ...)
        /Users/hiro/Decenter/lilypad/pkg/jobcreator/run.go:39 +0x1ac
github.com/bacalhau-project/lilypad/cmd/lilypad.runJob(_, {{0x0}, {{{0x0, 0x0}, {0x140001afdc0, 0x32}, {0x16ee23384, 0xc}, {0x1017059e9, 0x19}}, ...}, ...})
        /Users/hiro/Decenter/lilypad/cmd/lilypad/run.go:89 +0x3c0
github.com/bacalhau-project/lilypad/cmd/lilypad.newRunCmd.func1(0x14000237700?, {0x1400020def0?, 0x4?, 0x1016f4da1?})
        /Users/hiro/Decenter/lilypad/cmd/lilypad/run.go:33 +0xdc
github.com/spf13/cobra.(*Command).execute(0x14000426900, {0x1400020dea0, 0x5, 0x5})
        /Users/hiro/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x14000426000)
        /Users/hiro/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/hiro/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bacalhau-project/lilypad/cmd/lilypad.Execute()
        /Users/hiro/Decenter/lilypad/cmd/lilypad/root.go:33 +0xb0
main.main()
        /Users/hiro/Decenter/lilypad/main.go:8 +0x1c

```

Commit: `d1dd20720338daa51c187b2810f88d2913209025`
Branch: bugfix/github-tags-not-found
PR: #19

**Comment by Nasfame** [comment]
Just checked template is crashing the build from `main` branch

**Comment by Nasfame** [comment]
@lukemarsden

**Comment by Nasfame** [comment]
```
lilypad run github.com/DeCenter-AI/compute.decenter-ai:v1.7.1-alpha -i trainScript=headbrain.ipynb -i inputCid=Qme1HnwLHVzRxra7mT5gRkG7WbyE4FhnGFn9inETSj33Hw

⠀⠀⠀⠀⠀⠀⣀⣤⣤⢠⣤⣀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢴⣿⣿⣿⣿⢸⣿⡟⠀⠀⠀⠀⠀    ██╗     ██╗██╗  ██╗   ██╗██████╗  █████╗ ██████╗ 
⠀⠀⣰⣿⣦⡙⢿⣿⣿⢸⡿⠀⠀⠀⠀⢀⠀    ██║     ██║██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
⠀⢰⣿⣿⣿⣿⣦⡙⣿⢸⠁⢀⣠⣴⣾⣿⡆    ██║     ██║██║   ╚████╔╝ ██████╔╝███████║██║  ██║
⠀⣛⣛⣛⣛⣛⣛⣛⠈⠀⣚⣛⣛⣛⣛⣛⣛    ██║     ██║██║    ╚██╔╝  ██╔═══╝ ██╔══██║██║  ██║
⠀⢹⣿⣿⣿⣿⠟⣡⣿⢸⣮⡻⣿⣿⣿⣿⡏    ███████╗██║███████╗██║   ██║     ██║  ██║██████╔╝
⠀⠀⢻⣿⡟⣩⣾⣿⣿⢸⣿⣿⣌⠻⣿⡟⠀    ╚══════╝╚═╝╚══════╝╚═╝   ╚═╝     ╚═╝  ╚═╝╚═════╝ v2
⠀⠀⠀⠉⢾⣿⣿⣿⣿⢸⣿⣿⣿⡷⠈⠀⠀                                                  
⠀⠀⠀⠀⠀⠈⠙⠛⠛⠘⠛⠋⠁⠀ ⠀⠀⠀   Decentralized Compute Network  https://lilypad.tech

🌟  Lilypad submitting job
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x100f65794]

goroutine 1 [running]:
text/template.(*Template).init(...)
	/usr/local/go/src/text/template/template.go:71
text/template.(*Template).Funcs(0x0, 0x140005966f8?)
	/usr/local/go/src/text/template/template.go:178 +0x34
github.com/bacalhau-project/lilypad/pkg/module.LoadModule({{0x0, 0x0}, {0x14000139dc0, 0x32}, {0x16f26b3ef, 0xc}, {0x1012bda11, 0x19}}, 0x1400043a000?)
	/Users/hiro/Decenter/lilypad/pkg/module/utils.go:220 +0x290
github.com/bacalhau-project/lilypad/pkg/jobcreator.(*JobCreator).GetJobOfferFromOptions(_, {{{0x0, 0x0}, {0x14000139dc0, 0x32}, {0x16f26b3ef, 0xc}, {0x1012bda11, 0x19}}, {0x0, ...}, ...})
	/Users/hiro/Decenter/lilypad/pkg/jobcreator/jobcreator.go:76 +0x64
github.com/bacalhau-project/lilypad/pkg/jobcreator.RunJob(_, {{0x0}, {{{0x0, 0x0}, {0x14000139dc0, 0x32}, {0x16f26b3ef, 0xc}, {0x1012bda11, 0x19}}, ...}, ...}, ...)
	/Users/hiro/Decenter/lilypad/pkg/jobcreator/run.go:39 +0x1ac
github.com/bacalhau-project/lilypad/cmd/lilypad.runJob(_, {{0x0}, {{{0x0, 0x0}, {0x14000139dc0, 0x32}, {0x16f26b3ef, 0xc}, {0x1012bda11, 0x19}}, ...}, ...})
	/Users/hiro/Decenter/lilypad/cmd/lilypad/run.go:89 +0x3c0
github.com/bacalhau-project/lilypad/cmd/lilypad.newRunCmd.func1(0x140001c1700?, {0x14000195ef0?, 0x4?, 0x1012acde1?})
	/Users/hiro/Decenter/lilypad/cmd/lilypad/run.go:33 +0xdc
github.com/spf13/cobra.(*Command).execute(0x140003ae900, {0x14000195ea0, 0x5, 0x5})
	/Users/hiro/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x140003ae000)
	/Users/hiro/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/hiro/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bacalhau-project/lilypad/cmd/lilypad.Execute()
	/Users/hiro/Decenter/lilypad/cmd/lilypad/root.go:33 +0xb0
main.main()
	/Users/hiro/Decenter/lilypad/main.go:8 +0x1c
```
