### ISSUE TITLE
cli doesn't work on ipv6 only linux

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/lilypad#68]
my laptop has a 5G modem and my provider only gives me an IPv6 address

I have [configured docker to work with ipv6](https://zenofx.com/snippets/docker/docker-ipv6/), however, running the CLI fails thusly:

```
luke@floating:~/pf/franchise-cloud-platform$ lilypad run sdxl:v0.9-lilypad1 '{"prompt": "an astronaut riding on a tiny unicorn riding an elephant", "seed": 1}'

🌟 Lilypad submitting job sdxl:v0.9-lilypad1({"prompt": "an astronaut riding on a tiny unicorn riding an elephant", "seed": 1}) 🌟

▐ ⠂      ▌ Connecting to smart contractTraceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 200, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 388, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7efcaed7d2d0>: Failed to resolve 'testnet.lilypadnetwork.org' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='testnet.lilypadnetwork.org', port=8545): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7efcaed7d2d0>: Failed to resolve 'testnet.lilypadnetwork.org' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/modicum", line 33, in <module>
    sys.exit(load_entry_point('Modicum', 'console_scripts', 'modicum')())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/modicum/cli.py", line 702, in runLilypadCLI
    JC.platformConnect(_CONTRACT_ADDRESS_, _GETHIP_, _GETHPORT_, index)
  File "/app/modicum/PlatformClient.py", line 45, in platformConnect
    self.ethclient = EthereumClient(ip=geth_ip, port=geth_port)
  File "/app/modicum/EthereumClient.py", line 130, in __init__
    self.filter = self.w3.eth.filter({"fromBlock": self.w3.eth.block_number})
  File "/usr/local/lib/python3.10/dist-packages/web3/eth/eth.py", line 133, in block_number
    return self.get_block_number()
  File "/usr/local/lib/python3.10/dist-packages/web3/module.py", line 68, in caller
    result = w3.manager.request_blocking(
  File "/usr/local/lib/python3.10/dist-packages/web3/manager.py", line 231, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/manager.py", line 175, in _make_request
    return request_func(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/formatting.py", line 99, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/gas_price_strategy.py", line 96, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/formatting.py", line 99, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/attrdict.py", line 38, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/formatting.py", line 99, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/formatting.py", line 99, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/formatting.py", line 99, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/buffered_gas_estimate.py", line 43, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/middleware/exception_retry_request.py", line 107, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.10/dist-packages/web3/providers/rpc.py", line 90, in make_request
    raw_response = make_post_request(
  File "/usr/local/lib/python3.10/dist-packages/web3/_utils/request.py", line 114, in make_post_request
    response = get_response_from_post_request(endpoint_uri, data=data, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/web3/_utils/request.py", line 107, in get_response_from_post_request
    response = session.post(endpoint_uri, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='testnet.lilypadnetwork.org', port=8545): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7efcaed7d2d0>: Failed to resolve 'testnet.lilypadnetwork.org' ([Errno -3] Temporary failure in name resolution)"))
```

this happens even after `sudo systemctl restart docker`

from my laptop (someone somewhere, maybe EE, is inventing magical AAAA records)

```
luke@floating:~/pb/lilypad$ host testnet.lilypadnetwork.org
testnet.lilypadnetwork.org has address 34.30.95.3
testnet.lilypadnetwork.org has IPv6 address 64:ff9b::221e:5f03
```

(from another machine:
```
root@bravo-testnet-vm-0:/data/lilypad# host testnet.lilypadnetwork.org
testnet.lilypadnetwork.org has address 34.30.95.3
```
)

hmm, maybe i need to set the DNS servers that docker passes on to its containers to use the ones which can reach the magical AAAA addresses?

ohh, inside the container apt hangs, too...
```
root@d9524dfca134:/app# apt update && apt install -y dig
0% [Working]
```

ugh, maybe i just need to reboot

![image](https://github.com/bacalhau-project/lilypad/assets/264658/118f14bb-9607-4844-82c5-1c4cefd3648a)

**Comment by lukemarsden** [comment]
not actually a problem with our software
